# Generated by Django 5.1.2 on 2024-12-17 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTAProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('suitebook_id', models.IntegerField()),
                ('aos_slug', models.CharField(max_length=255, unique=True)),
                ('aos_organization_name', models.CharField(max_length=255)),
                ('aos_organization_slug', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Property Profile',
                'verbose_name_plural': 'Property Profiles',
                'db_table': 'property_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('channel_id', models.IntegerField()),
                ('f_no', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credential.otaprofile')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credential.propertyprofile')),
            ],
            options={
                'db_table': 'credentials',
                'indexes': [models.Index(fields=['property_id', 'ota_id', 'username'], name='credentials_propert_7cc00a_idx')],
            },
        ),
    ]
