# Generated by Django 5.1.2 on 2025-01-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credential', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyprofile',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
